[tool.micropython]
port = "/dev/ttyUSB0"
board = "esp32"

[tool.ruff]
# Enable Ruff formatter
target-version = "py39"
# Line length to match common MicroPython conventions
line-length = 100
# Exclude certain directories
exclude = [
    ".git",
    ".ruff_cache",
    "__pycache__",
    "venv",
]

# Enable auto-fixing of all rules
fix = true

[tool.ruff.lint]
# Include all Ruff rules by default
select = ["E", "F", "W", "I", "N", "UP", "B", "C4", "SIM", "RUF"]
# Allow fixing all fixable rules
unfixable = []

[tool.ruff.lint.per-file-ignores]
# Ignore unused imports in __init__.py files
"__init__.py" = ["F401"]
# Ignore some rules in test files
"test_*.py" = ["E501"]

[tool.ruff.lint.isort]
# Configure import sorting
known-first-party = ["lib"]

[tool.ruff.format]
# Quote style (', ", ''', or """)
quote-style = "single"
# Indent with 4 spaces
indent-style = "space"
line-ending = "auto"
