# MicroPython time module stub

def sleep(seconds: float) -> None: ...
def sleep_ms(ms: int) -> None: ...
def sleep_us(us: int) -> None: ...
def ticks_ms() -> int: ...
def ticks_us() -> int: ...
def ticks_cpu() -> int: ...
def ticks_add(ticks: int, delta: int) -> int: ...
def ticks_diff(ticks1: int, ticks2: int) -> int: ...
def time() -> int: ...
def localtime(secs: int | None = None) -> tuple[int, int, int, int, int, int, int, int]: ...
def mktime(tuple: tuple[int, int, int, int, int, int, int, int]) -> int: ...
def gmtime(secs: int | None = None) -> tuple[int, int, int, int, int, int, int, int]: ...
