# MicroPython time module stub

from typing import Tuple, Optional, Union

def sleep(seconds: float) -> None: ...
def sleep_ms(ms: int) -> None: ...
def sleep_us(us: int) -> None: ...

def ticks_ms() -> int: ...
def ticks_us() -> int: ...
def ticks_cpu() -> int: ...
def ticks_add(ticks: int, delta: int) -> int: ...
def ticks_diff(ticks1: int, ticks2: int) -> int: ...

def time() -> int: ...
def localtime(secs: Optional[int] = None) -> Tuple[int, int, int, int, int, int, int, int]: ...
def mktime(tuple: Tuple[int, int, int, int, int, int, int, int]) -> int: ...
def gmtime(secs: Optional[int] = None) -> Tuple[int, int, int, int, int, int, int, int]: ...